# Generated by Django 4.2.2 on 2023-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveLife_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
